trigger:
- main

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: DockerBuildAndPush
    displayName: Build and Push
    pool:
      name: 'Default'

    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'DockerHub'  # Nome do service connection configurado no Azure DevOps
        repository: 'dividino/agendeja-web'  
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(Build.BuildId)
